spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_order
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 'data' को 'spring' के अंदर ही होना चाहिए
  data:
    web:
      pageable:
        serialization-mode: via_dto

# 'management' बिलकुल बाहर (Top-level) रहेगा
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true